### PR TITLE
Setup 2.x branch for Buster

### PR DESCRIPTION
**Pull request by naruxde**
I opened the 2.x branch on tag 2.0.0. The branch devel/ssager/setup_2x_branch is on the last commit that is compatible with version 2.x. Please check if this fits.

### CODE REVIEW

**Review by nbuchwitz — APPROVED** [review]
Lgtm, but I'm wondering why we needs this branch? Imho it is unlikely that we will change the repo files for Buster (see history: one release for stretch, two for Buster).

**Comment by naruxde** [comment]
It illustrates our handling of a "breaking change" to other employees and developers. As we don't use a kind of [Conventional Commits](Https://www.conventionalcommits.org/en/v1.0.0/) for our commit messages, it easily can happen to merge the main branch to a wrong raspios release.
This can be seen as a kind of demo, which we should do immediately as soon as a `BREAKING CHANGE:` happens.

**Review by RamiGspo — APPROVED** [review]

**Comment by iluminat23** [comment]
I though we decided against creating a y.x branch in every repo. The Idea with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and the breaking changes is nice though. Much better then creating unused y.x branches in every repo.
Also it doesn't protect against any releases with conflicting versions

**Review by iluminat23 — COMMENTED** [review]
NAK

**Pull request merged**
